Draft: Reset the file path after clean the buffer
xenodium/chatgpt-shell pull request #228
Opened 2024-08-24 19:30 UTC by ccqpein

Try to implement the issue #227 .

After `(setf shell-maker-if-file-path-reset-after-clean 'reset)` and manually binding the `("C-c M-o" . chatgpt-shell-clear-buffer)`. It will reset the `shell-maker--file`to `nil` after I clean the buffer. So I can save the new conversation in new file. 

**Feel free to change it if it isn't match the design of **owner.**

2024-08-27 20:03 UTC, xenodium requested changes
Thanks for the draft!

Left a few comments. Also, be sure to run `M-x checkdoc` and byte compile the files (can do it from dired via `M-x dired-do-byte-compile`).

I'm aware of a few warnings in the compilation. Let's try not to add more ;)

2024-08-28 00:26 UTC, ccqpein commented on shell-maker.el
> +  (pcase shell-maker-if-file-path-reset-after-clean
I was thinking `chatgpt-shell` don't `setq` `shell-maker` var directly. But I notice it already `setq` some var now.

2024-08-28 07:23 UTC, xenodium commented on shell-maker.el
> +  "Tell the shell-maker-save-session-transcript reset file path or not.
My bad, I made a typo: shell-maker-forget-file-after-cleaR

2024-08-28 07:56 UTC, xenodium requested changes
Thank you for the changes! Left some minor comments if you're keen to address. Otherwise, I'll follow up.

2024-08-28 07:56 UTC, xenodium commented on chatgpt-shell.el
> +  "Clean the current shell buffer."
nit: Clea*r*

2024-08-28 07:56 UTC, xenodium commented on shell-maker.el
> +  "Tell the `shell-maker-save-session-transcript' reset file path or not."
nit: Consider "If non-nil, reset file path after clear command." as other booleans in this file.

ps. Heads-up, I've just made https://github.com/xenodium/chatgpt-shell/commit/54f31661df1c44e16638c8ff1e457573ea3ef7cd which is more idiomatic.

2024-08-28 14:03 UTC, ccqpein commented on chatgpt-shell.el
> +  "Clean the current shell buffer."
Just give the new commit.

2024-08-28 14:15 UTC, xenodium approved these changes
Thanks for the changes and the PR!

2024-08-28 14:15 UTC, merged

2024-08-28 14:17 UTC, ccqpein commented
No problem

2024-08-28 14:34 UTC, xenodium commented
A couple of follow-ups:

- We need to move it to shell-maker to make it compatible with the "clear" shell command: https://github.com/xenodium/chatgpt-shell/commit/a342d3398f4ffa1fce875adf9016fe63155d85ed
- Typo: https://github.com/xenodium/chatgpt-shell/commit/2f5525553a97567c1805d787880af290f8cfc926